ALTER TABLE STAFF_EXCEPTIONS DROP COLUMN MODCAT;
ALTER TABLE STAFF_EXCEPTIONS DROP COLUMN TITLE;
ALTER TABLE STAFF_EXCEPTIONS ADD COLUMN CAN_USE VARCHAR(1);
ALTER TABLE STAFF_EXCEPTIONS ADD COLUMN CAN_EDIT VARCHAR(1);
CREATE INDEX STAFF_EXCEPTIONS_IND1 ON STAFF_EXCEPTIONS (USERNAME,MODNAME,CAN_EDIT);
CREATE INDEX STAFF_EXCEPTIONS_IND2 ON STAFF_EXCEPTIONS (CAN_USE);